FROM python:3.6.3 

# install environment dependencies 
RUN apt-get update -yqq \
&& apt-get install -yqq --no-install-recommends \
netcat vim \ 
&& apt-get -q clean 

# set working directory 
RUN mkdir -p /usr/src/app 
WORKDIR /usr/src/app 

# add app 
ADD . /usr/src/app 

# install requirements 
RUN pip install -r requirements.txt 

# run server 
CMD ["sh","-c","chmod 777 /usr/src/app/entrypoint.sh && /usr/src/app/entrypoint.sh"] 
